name: mirror 

on:
  push:
    branches: main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/bricked/pages.git'
          GIT_USERNAME: bricked
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
